<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.5.13.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuizMakerDAL\QuizMakerDAL.csproj" />
    <ProjectReference Include="..\QuizMakerModel\QuizMakerModel.csproj" />
  </ItemGroup>

</Project>
